name: "Pull Request Build"
on:
  - pull_request
jobs:
  linux-build-ocp-s2i:
    name: PR - Linux - JVM ${{ matrix.java }} - OpenShift ${{ matrix.openshift }} - S2i
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
        openshift: [ v3.11.0 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Print slug/short variables
        run: |
          echo "GitHub variables"
          echo " - ${{ github.ref }}"
          echo " - ${{ github.head_ref }}"
          echo " - ${{ github.base_ref }}"
          echo "Slug variables"
          echo " - ${{ env.GITHUB_REF_SLUG }}"
          echo " - ${{ env.GITHUB_HEAD_REF_SLUG }}"
          echo " - ${{ env.GITHUB_BASE_REF_SLUG }}"
          echo " - ${{ env.GITHUB_REPOSITORY_SLUG }}"
          # output e.g. : master feat-new-feature v1.0.0 product-1.0.0-rc.2 new-awesome-product
          echo "Slug URL variables"
          echo " - ${{ env.GITHUB_REF_SLUG_URL }}"
          echo " - ${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
          echo " - ${{ env.GITHUB_BASE_REF_SLUG_URL }}"
          echo " - ${{ env.GITHUB_REPOSITORY_SLUG_URL }}"
          # output e.g. : master feat-new-feature v1-0-0 product-1-0-0-rc-2 new-awesome-product
          echo "Short SHA variables"
          echo " - ${{ env.GITHUB_SHA_SHORT }}"
          # output e.g. : ffac537e
      - uses: FranzDiebold/github-env-vars-action@v1.2.0
      - name: Print environment variables
        run: |
          echo "GITHUB_REPOSITORY_SLUG=$GITHUB_REPOSITORY_SLUG"
          echo "GITHUB_REPOSITORY_OWNER=$GITHUB_REPOSITORY_OWNER"
          echo "GITHUB_REPOSITORY_OWNER_SLUG=$GITHUB_REPOSITORY_OWNER_SLUG"
          echo "GITHUB_REPOSITORY_NAME=$GITHUB_REPOSITORY_NAME"
          echo "GITHUB_REPOSITORY_NAME_SLUG=$GITHUB_REPOSITORY_NAME_SLUG"
          echo "GITHUB_REF_SLUG=$GITHUB_REF_SLUG"
          echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
          echo "GITHUB_REF_NAME_SLUG=$GITHUB_REF_NAME_SLUG"
          echo "GITHUB_SHA_SHORT=$GITHUB_SHA_SHORT"

